/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { Suspense} from "react";
import { Asset } from '../Asset';
import { useConfiguratorStore } from "@/store/store";

export function Tree({...props}) {
    const customization = useConfiguratorStore((state) => state.customization);
    
    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                {Object.keys(customization).map((key) => {
                    if (customization[key]?.asset?.url) {

                        return (
                            <Suspense key={customization[key].asset.id}>
                                <Asset
                                    categoryName={key}
                                    url={customization[key].asset.url}
                                />
                            </Suspense>
                        );
                    }
                    return null;
                })}
            </group>
        </group>
    )
}
